server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: hexagonal
#      uri: mongodb://localhost:27017/hexagonal